import Foundation

/// Lightweight summary returned by `voice_memo.list_recordings`.
public struct VoiceMemoSummary: Codable, Sendable, Hashable {
    /// Stable UUID from `ZUNIQUEID` (preserved across iCloud sync).
    public let id: String
    /// User-provided title if set, else the auto-generated date label.
    public let title: String
    /// ISO 8601 UTC.
    public let recordedAt: String
    /// Duration in seconds (float, sub-second precision).
    public let durationSeconds: Double
    /// Filename under the Recordings dir (e.g. "20260225 125605-ADB2C813.m4a").
    public let filename: String
    /// True when the .m4a file is materialized locally; false if it's an
    /// .icloud placeholder waiting to download.
    public let hasLocalFile: Bool
    public let fileSizeBytes: Int64?

    public init(
        id: String, title: String, recordedAt: String,
        durationSeconds: Double, filename: String,
        hasLocalFile: Bool, fileSizeBytes: Int64?
    ) {
        self.id = id
        self.title = title
        self.recordedAt = recordedAt
        self.durationSeconds = durationSeconds
        self.filename = filename
        self.hasLocalFile = hasLocalFile
        self.fileSizeBytes = fileSizeBytes
    }

    enum CodingKeys: String, CodingKey {
        case id, title
        case recordedAt = "recorded_at"
        case durationSeconds = "duration_seconds"
        case filename
        case hasLocalFile = "has_local_file"
        case fileSizeBytes = "file_size_bytes"
    }
}

/// Detail for `voice_memo.get_recording` — adds the resolved absolute path so
/// other tools / scripts could touch the audio directly.
public struct VoiceMemoDetail: Codable, Sendable {
    public let id: String
    public let title: String
    public let recordedAt: String
    public let durationSeconds: Double
    public let filename: String
    public let absolutePath: String
    public let hasLocalFile: Bool
    public let fileSizeBytes: Int64?
    public let folderUUID: String?
    public let autoGeneratedLabel: String?     // ZCUSTOMLABEL — date-shaped fallback name

    public init(
        id: String, title: String, recordedAt: String,
        durationSeconds: Double, filename: String, absolutePath: String,
        hasLocalFile: Bool, fileSizeBytes: Int64?,
        folderUUID: String?, autoGeneratedLabel: String?
    ) {
        self.id = id
        self.title = title
        self.recordedAt = recordedAt
        self.durationSeconds = durationSeconds
        self.filename = filename
        self.absolutePath = absolutePath
        self.hasLocalFile = hasLocalFile
        self.fileSizeBytes = fileSizeBytes
        self.folderUUID = folderUUID
        self.autoGeneratedLabel = autoGeneratedLabel
    }

    enum CodingKeys: String, CodingKey {
        case id, title
        case recordedAt = "recorded_at"
        case durationSeconds = "duration_seconds"
        case filename
        case absolutePath = "absolute_path"
        case hasLocalFile = "has_local_file"
        case fileSizeBytes = "file_size_bytes"
        case folderUUID = "folder_uuid"
        case autoGeneratedLabel = "auto_generated_label"
    }
}

/// Output of `voice_memo.read_audio` — caller decodes base64 to get the .m4a.
public struct VoiceMemoAudio: Codable, Sendable {
    public let id: String
    public let filename: String
    public let mime: String           // "audio/mp4" for .m4a
    public let encoding: String       // always "base64" for now
    public let bytesRead: Int64
    public let totalBytes: Int64
    public let truncated: Bool
    public let content: String        // base64 of the bytes read
    public init(
        id: String, filename: String, mime: String, encoding: String,
        bytesRead: Int64, totalBytes: Int64, truncated: Bool, content: String
    ) {
        self.id = id
        self.filename = filename
        self.mime = mime
        self.encoding = encoding
        self.bytesRead = bytesRead
        self.totalBytes = totalBytes
        self.truncated = truncated
        self.content = content
    }

    enum CodingKeys: String, CodingKey {
        case id, filename, mime, encoding, content, truncated
        case bytesRead = "bytes_read"
        case totalBytes = "total_bytes"
    }
}
